### ISSUE TITLE
Suggested User Agent

### ISSUE THREAD

**Issue by betillogalvanfbc** [onemanbuilds/SpotifyChecker#2]
You can replace these line to use a library for generated random agent
Line 118
  headers = {
            'User-Agent': self.GetRandomUserAgent()
        }
https://pypi.org/project/fake-useragent/    
from fake_useragent import UserAgent
ua = UserAgent()
  headers = {
            'User-Agent': self.ua.random
        }

**Comment by onemanbuilds** [comment]
i know how to change useragents but thanks :D

**Comment by LARSABI** [comment]
> i know how to change useragents but thanks :D

Could you add it to your Acc Creator?

**Comment by onemanbuilds** [comment]
why is it needed? the accounts will be banned with random useragents too.
